version: '3.8'
networks:
  my-network:
    driver: bridge
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - my-network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: squad
  article:
    image: soldiers:latest
    container_name: soldiers
    ports:
      - "8090:8090"
    networks:
      - my-network
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
  stock:
    image: squad:latest
    container_name: squad
    ports:
      - "8089:8089"
    depends_on:
      - discovery-server
    environment:
      environment:
      SPRING_APPLICATION_JSON: '{
          "spring.application.name" : "Stock-MS",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.datasource.url" : "jdbc:mysql://localhost:3306/squad?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "root",
          "server.port" : "8089",
          "eureka.client.service-url.defaultZone" : "http://localhost:8761/eureka/",
          "eureka.client.register-with-eureka" : "true",
          "eureka.client.fetch-registry" : "true",
          "eureka.instance.lease-renewal-interval-in-seconds" : "30",
          "eureka.instance.lease-expiration-duration-in-seconds" : "90",
          "eureka.instance.prefer-ip-address" : "true"
      }'
      stdin_open: true
      tty: true

  apigateway:
    image: apigateway:latest
    container_name: apigateway
    ports:
      - "8875:8875"
    networks:
      - my-network
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
  discovery-server:
    image: discovery-server:latest
    container_name: discovery-server
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    ports:
      - "8761:8761"
    networks:
      - my-network

